export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
  }
export default function layout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  )
}
