
import { Suspense } from "react"
import Products from "../../components/user/AllProductsComponents/Products"

export const metadata = {
  title: 'Products',
  description: 'Generated by create next app',
}
export default function page() {
  return (
    <div>
      <Suspense fallback={<div>Loading Products...</div>}>
        <Products />
      </Suspense>
    </div>
  )
}