import Products from "@/app/components/user/AllProductsComponents/Products"

export const metadata = {
  title: 'Products',
  description: 'Generated by create next app',
}
export default function page() {
  return(
    <Products/>
  )
}